# Generated by Django 3.0.2 on 2022-02-09 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=254, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=254, null=True)),
                ('last_name', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('date_joined', models.DateTimeField(null=True)),
                ('credit_line', models.PositiveIntegerField(default=0, verbose_name='Credit Line')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Amount')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
            },
        ),
        migrations.CreateModel(
            name='CutOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(verbose_name='Date')),
                ('is_done', models.BooleanField(default=False, verbose_name='Done')),
            ],
            options={
                'verbose_name': 'Cut Off',
                'verbose_name_plural': 'Cut Offs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField()),
                ('reference_number', models.CharField(max_length=50)),
                ('is_done', models.BooleanField(default=False, verbose_name='Done')),
            ],
            options={
                'verbose_name': 'Procurement',
                'verbose_name_plural': 'Procurements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('factor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Factor')),
                ('label', models.CharField(max_length=5)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='app.Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Remittance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('date', models.DateField(null=True)),
                ('expenses', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('cash', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('coins', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_locked', models.BooleanField(default=False, verbose_name='Locked')),
                ('notes', models.TextField(blank=True, null=True)),
                ('with_ar', models.BooleanField(default=True, verbose_name='With A/R')),
            ],
            options={
                'verbose_name': 'Remittance',
                'verbose_name_plural': 'Remittances',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Supplier',
                'verbose_name_plural': 'Suppliers',
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_online', models.BooleanField(default=True, verbose_name='Online')),
                ('status', model_utils.fields.StatusField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('for_pick_up', 'For Pick Up'), ('complete', 'Complete')], default='pending', max_length=100, no_check_for_status=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_ar', models.BooleanField(default=True, verbose_name='A/R')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True)),
                ('or_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='OR Number')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('remittance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='app.Remittance')),
            ],
            options={
                'verbose_name': 'Sale',
                'verbose_name_plural': 'Sales',
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('procurement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app.Procurement')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='app.Product')),
            ],
            options={
                'verbose_name': 'Purchase',
                'verbose_name_plural': 'Purchases',
            },
        ),
        migrations.AddField(
            model_name='procurement',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procurements', to='app.Supplier'),
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.Product')),
            ],
            options={
                'verbose_name': 'Price',
                'verbose_name_plural': 'Prices',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_type', models.CharField(blank=True, choices=[('P', 'Percent'), ('C', 'Count')], max_length=1, null=True)),
                ('discount_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Quantity')),
                ('prev_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Prev Quantity')),
                ('is_modified', models.BooleanField(default=False, verbose_name='Modified')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.Price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.Product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='app.Sale')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Debit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Amount')),
                ('is_paid', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='app.Collection', verbose_name='Collection')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debits', to='app.Sale', verbose_name='Sale')),
            ],
            options={
                'verbose_name': 'Debit',
                'verbose_name_plural': 'Debits',
                'ordering': ['-sale'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='cut_off',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='app.CutOff', verbose_name='Cut Off'),
        ),
        migrations.CreateModel(
            name='Adjustment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('quantity', models.FloatField(default=0)),
                ('notes', models.TextField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustments', to='app.Product')),
            ],
            options={
                'verbose_name': 'Adjustment',
                'verbose_name_plural': 'Adjustments',
            },
        ),
    ]
